### ISSUE TITLE
Calculate entry point

### ISSUE THREAD

**Issue by circutrider21** [serge1/COFFI#8]
I was wondering, is there a way to calculate the entry point of a PE executable in file offset form. Like for example...
````assembly
; Entry at 0x1000 or 4096
mov rsp, rbp
````
How would I go about that?

**Comment by serge1** [comment]
Hi, you may try using get_ip() function belonging to dos_header class. get_sp() function will provide the initial value of the stack pointer.

Please confirm. Thank you

**Comment by circutrider21** [comment]
Thanks, worked like a charm!
