### ISSUE TITLE
mingw53 compilation error  

### ISSUE THREAD

**Issue by neomissing** [serge1/COFFI#9]
error: use of deleted function 'COFFI::coffi_strings::coffi_strings(const COFFI::coffi_strings&)'

**Comment by serge1** [comment]
Hi, in case the problem is observed only when compiled with a specific tool chain, it does not sound like a library problem.
would you please provide more information about this issue and conditions for reprodusing?

**Comment by neomissing** [comment]
> Hi, in case the problem is observed only when compiled with a specific tool chain, it does not sound like a library problem. would you please provide more information about this issue and conditions for reprodusing?

Qt5.7.0 mingw53

**Comment by serge1** [comment]
I am sorry, I didn't manage to create this compilation environment. As no similar requests have been received, and due to inactivity during last 1.5 years, I am closing the issue. Please reopen if you think that it is still relevant.
